_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
epochs:
    value: 20
model:
    value: SGDClassifier
train_size:
    value: 5011
valid_size:
    value: 556
vectorizer:
    value: TfidfVectorizer
